### ISSUE TITLE
DBM::Deep error

### ISSUE THREAD

**Issue by etwatson** [sestaton/Transposome#24]
#### Background
I've been running into memory issues, with all of my 32G consumed during the PairFinder.pm step. I sampled 100000 SE reads and even use a smaller Repbase library, splitting different TE classes into independent runs and setting `in_memory = 0`. Below is my config file:

```
#### Transposome version: 0.09.5
blast_input:
  - sequence_file:      SC_te-reads_1_100_000.fasta
  - sequence_format:    fasta
  - sequence_num:       10000
  - thread:             7
  - output_directory:   DNA_results_out
clustering_options:
  - in_memory:          0
  - percent_identity:   85
  - fraction_coverage:  0.55
annotation_input:
  - repeat_database:    /usr/share/repbase/DNA.fa
annotation_options:
  - cluster_size:       100
  - blast_evalue:       10
output:
  - run_log_file:       DNA_t_log.txt
  - cluster_log_file:   DNA_t_cluster_report.txt
```
#### Producing the output:
```
Transposome::Run::Blast::run_allvall_blast started at:   06-05-2015 14:15:35.
Transposome::Run::Blast::run_allvall_blast finished running mgblast on 100000 sequences in 15.71 minutes.
Transposome::Run::Blast::run_allvall_blast completed at: 06-05-2015 14:31:18. Final output file is:
SC_te-reads_1_100_000_allvall_blast.bln.
Transposome::PairFinder::parse_blast started at:   06-05-2015 14:31:18.
```
#### ...and the error:

`DBM::Deep: '171': Don't know what to do with type '�' at /usr/local/share/perl/5.18.2/Transposome/PairFinder.pm line 202`

I don't know much about how DBM::Deep works, but some [google searches](http://stackoverflow.com/questions/11368807/dbmdeep-unexplained-errors) informed me that problems stem from using a copy of a DBM::Deep object and that a new DBM::Deep object should be created in the child.

**Comment by sestaton** [comment]
Thanks for the report. I've never seen this error but I think it's not related to the link you provided (there are no forks or separate processes used in that step). The actual issue is that the module DBM::Deep has a memory leak (which I have reported). 

I have fixed this issue by removing this module and using a different indexing method. This code is on github on a development branch and I will try to finish up that work and make a new release tomorrow.

By the way, what type of input are you using with transposome? It is designed to work with WGS data and the amount of time spent on the blast step and the memory used is really unusual for just 100k reads.

**Comment by etwatson** [comment]
I ran a *de novo* k-mer based transposable element assembler to generate a TE library for my population sample (Illumina PE from pooled-DNA), then extracted the reads that mapped to that library. From those reads, I used your script to sample 100,000 reads.

**Comment by sestaton** [comment]
Ah! That explains the time spent on the blast step and the memory usage finding graph edges because the input is all repeats. Try transposome with 100,000 WGS random reads as the input. It should go very fast and not cause any issues. This version should work fine for that data, but let me know what you find with just the WGS data. I am going to leave this issue open because this general issue does need to be fixed.

**Comment by etwatson** [comment]
I've tried to get your read sampling script to work on the WGS data but I kept getting an `Out of memory!` error. I was able to use seqtk and Pairfq to properly sample 100000 reads. 
* note: seqtk stripped the pair information from the header lines and I had to add them back with a perl script. 
* also: pairfq returned `Use of uninitialized value $comm in concatenation (.) or string at /usr/local/bin/pairfq line 445, <$fh> line 400000.` for each line.
* This mgblast run took a lot less time: `Transposome::Run::Blast::run_allvall_blast finished running mgblast on 200000 sequences in 5.98 minutes.`

However, I still got the above DBM::Deep error during the PairFinder.pm step.

**Comment by sestaton** [comment]
I haven't compared the memory usage of seqtk and transposome, but they use the same algorithm and given the same random seed will produce the equivalent output. I can test this.

* The first problem you note is a well known issue. In the future, a way to fix that is with pairfq:

    pairfq addinfo -i reads.fq -o reads_1.fq -p 1

More information on that command is on the Pairfq [wiki](https://github.com/sestaton/Pairfq/wiki/addinfo).

* Can you show me a sample of your data with the `head` command? There are tests for the Pairfq code and I haven't seen this issue. Also, there are conditionals to see if that variable is defined so I'm not sure what could cause this without seeing the data.

* Great!

Okay, the fix I am working on now will solve that issue. I hoped to make a release today but the tests took longer than expected so it will be tomorrow at least.

**Comment by sestaton** [comment]
After more thought, your first comment confuses me. The sampling method would only keep 100k reads in memory at a time. Transposome likely uses slightly more memory than seqtk, but you should be able to do that analysis on a small laptop. There may be something irregular about your data format that isn't being parsed correctly and this could also cause the warnings from pairfq.

**Comment by sestaton** [comment]
@etwatson Please give the latest version a try. It should fix at least one of your issues. Also, please show a snippet of your fastq if you can. That will help me diagnose the issues you reported.

**Comment by etwatson** [comment]
@sestaton I reran the entire analysis with the latest version, 0.09.6, and received a new error during the annotation run. There are some annotations in the singleton reports, but all other reports are empty

```
INFO - Transposome::Annotation::annotate_clusters started at:   11-05-2015 15:43:35.
INFO - Transposome::Annotation::annotate_clusters completed at: 11-05-2015 15:43:55.
INFO - Results - Total sequences:                        200000
INFO - Results - Total sequences clustered:              37012
INFO - Results - Total sequences unclustered:            162988
INFO - Results - Repeat fraction from clusters:          0.18506
INFO - Results - Singleton repeat fraction:              0.000631948364296758
INFO - Results - Total repeat fraction:                  0.185575
INFO - Results - Total repeat fraction from annotations: 0
INFO - Transposome::Annotation::clusters_annotation_to_summary started at:   11-05-2015 15:43:55.
INFO - Transposome::Annotation::clusters_annotation_to_summary completed at: 11-05-2015 15:43:55.
Can't locate object method "from_epoch" via package "DateTime" at /usr/local/bin/transposome line 327.
```

Also, here are what my input reads look like:
```
@HWI-D00216:136:H8D1UADXX:1:2107:18373:52849 1
ATTATACATAAGATTTTGATAGAATTAGATAAAAACAACACAACTGCATTAAAATTTAGGAAAGAGGAATCGCCCCAATCGGCCCTTTATTTGGAAAGGC
+
CCCFFFFFHHHHHJJJJJIJJJIJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJIJJJJJJJHHFFDEEDCDDDDDDDDDEEDDDDDDD
@HWI-D00216:136:H8D1UADXX:1:2107:18373:52849 2
CTTTTCCTCGTTTGGCTACAGTAAATATTGTACTTTTAACCCATATAGCTCCCTTACTCTGCACGAAATATGGTTTACGATCTGCACTTCAGAGAGCGCT
+
CCCFFFFFHHHHHJJJJJJJJHJJJJJJJJIIJJJJJJJJJJJJJJJJIIJJJJJJJJJIIJJJJJJJJJJJHHHHHFFFFDEEEEEDDDDDDDDDDDDD
@HWI-D00216:136:H8D1UADXX:1:2113:2975:58935 1
GATCAATTTCTTTCTGTACTTTGTTACGATGATGGAAGTATTTTATCCAACATCCCAAATCAGATAGAAAAGGGTCAATCACATTAGATCGATTTAACTG
+
<@@;DDDDHHBFFIIIEEHICHIIDIGIIIIIIGEGIG:DGHGGFHIIGHIGIIIIIIGGFEHIEHIIIIIFIIEGEEHEHHEEEEDDCCCCBCBCCCCC
@HWI-D00216:136:H8D1UADXX:1:2113:2975:58935 2
CTTTTGAAATGAAATTGGTATAATTGAAGTACGTCAGTTAAATCGATCTAATGTGATTGACCCTTTTCTATCTGATTTGGGATGTTGGATAAAATACTTC
+
CCCFFFDDHHHHHJJIJIHIIJJJJJJJJHHIIHDFGGIIJIJJJHIIGGHJJBFGHGIIIJJIJJJGJIGJIIIEIIGHHHHFFFDFCEEEEEEDDDDD
```
Here are what the raw reads look like:
```
@HWI-D00216:136:H8D1UADXX:1:1101:1198:2444 1:N:0:GAGTGG
TTTTTTTGTTTTTTTTCCTTATTCGTTACTTGCTCTTTTAACAGCTTTAATAAGTCAGCATCACGAATAACATTATTCACATATTGACCTTTATCACTTC
+
@CCFFFFFHHHHHJJJIJJJIIJJJIJJIJJIIIJJJJJJJGHJJJHHFHHHHFFFFFFEEECDDDBDDDDDDDCDFDDDDCDEEECCDDDDCDDDDDDC
@HWI-D00216:136:H8D1UADXX:1:1101:1123:2450 1:N:0:GAGTGG
TTCCGATTTTGGAACGACAATTCGCTTGTTATGTATTAACAATAGTCCGCTGGATTGGTCCAAAGACAAATCCCCCCACTGTTTCGAGAAACATCTTGCT
+
@@@DFDFFHHFHHIGIIIJJIGHIIIJJIJHGEDFHIJIIIGHGIGGIIIGHIHIJFH?EEFFFFDEECCCEDDDDDDDDDCDDDDBCBDDDDDDDDDCC
```

**Comment by sestaton** [comment]
Can you show me how you installed Transposome? There appears to be something odd with the installation. Also, the output of the following command would be helpful:

    perl -MDateTime -e 'print DateTime->VERSION'

For the Pairfq warnings, I have uploaded a new version which handles this case (missing comment after pair id). The previous version produced the correct result but also generated warnings, which you reported.

**Comment by etwatson** [comment]
I installed Transposome 0.09.6 the same way that I installed the last version:
`curl -L cpanmin.us | perl - git://github.com/sestaton/Transposome.git`
Although the command you suggested indicated that I needed to install Params::Validate. After installing this, the annotation ran without error.  The repeat fraction calculated from only 10,000 is less than what I expected from other analyses, so I will re-run Transposome with a larger sample of reads. 

```
>perl -MDateTime -e 'print DateTime->VERSION'
Can't locate Params/Validate.pm in @INC (you may need to install the Params::Validate module) (@INC contains: /etc/perl /usr/local/lib/perl/5.18.2 /usr/local/share/perl/5.18.2 /usr/lib/perl5 /usr/share/perl5 /usr/lib/perl/5.18 /usr/share/perl/5.18 /usr/local/lib/site_perl .) at /usr/local/lib/perl/5.18.2/DateTime/Duration.pm line 9.
BEGIN failed--compilation aborted at /usr/local/lib/perl/5.18.2/DateTime/Duration.pm line 9.
Compilation failed in require at /usr/local/lib/perl/5.18.2/DateTime.pm line 12.
BEGIN failed--compilation aborted at /usr/local/lib/perl/5.18.2/DateTime.pm line 12.
Compilation failed in require.
BEGIN failed--compilation aborted.
```
```
INFO - Transposome::Annotation::annotate_clusters started at:   12-05-2015 10:11:22.
INFO - Transposome::Annotation::annotate_clusters completed at: 12-05-2015 10:11:39.
INFO - Results - Total sequences:                        200000
INFO - Results - Total sequences clustered:              37012
INFO - Results - Total sequences unclustered:            162988
INFO - Results - Repeat fraction from clusters:          0.18506
INFO - Results - Singleton repeat fraction:              0.000631948364296758
INFO - Results - Total repeat fraction:                  0.185575
INFO - Results - Total repeat fraction from annotations: 0
INFO - Transposome::Annotation::clusters_annotation_to_summary started at:   12-05-2015 10:11:39.
INFO - Transposome::Annotation::clusters_annotation_to_summary completed at: 12-05-2015 10:11:39.
INFO - ======== Transposome completed at: 12-05-2015 10:11:48. Elapsed time: 26 seconds. ========
```

**Comment by etwatson** [comment]
Thank you @sestaton for all of your help and attention, I am now able to run transposome on my reads, and will be citing your work in our upcoming genome paper.

**Comment by sestaton** [comment]
Thanks for the report, I try to understand why that one dependencies wasn't installed. From the looks of your results I suspect the repeat database may not be in the correct format because the repeat content from annotations is reported as 0. Can you show me the header of the repeat database fasta file? 
Also, it looks like this ran very quick, my suggestions would be to first solve the repeat database format (there is a script in the [transposome-scripts](https://github.com/sestaton/transposome-scripts)) repository which I can help with) and then use a larger sample of sequences.

**Comment by etwatson** [comment]
Thanks for the suggestion. My repeat database didn't have the correct format, and fixing that helped with the annotation issue.

**Comment by sestaton** [comment]
Great. I'll close this issue to avoid confusion since DBM::Deep is no longer used.
