### ISSUE TITLE
Louvain 'community' failed.

### ISSUE THREAD

**Issue by etwatson** [sestaton/Transposome#28]
After ~12 hours the Cluster algorithm is failing:

```
INFO - ======== Transposome version: 0.09.6 (started at: 28-05-2015 23:49:52) ========
INFO - Configuration - Log file for monitoring progress and errors: ArthroTE_300k_t_log.txt
INFO - Configuration - Sequence file:                               /home/eric/tigriopus_genome/AB_150k.interleaved.fastq
INFO - Configuration - Sequence format:                             fastq
INFO - Configuration - Sequence number for each BLAST process:      10000
INFO - Configuration - Number of CPUs per thread:                   1
INFO - Configuration - Number of threads:                           7
INFO - Configuration - Output directory:                            AB_300k_results_out
INFO - Configuration - In-memory analysis:                          0
INFO - Configuration - Percent identity for matches:                85
INFO - Configuration - Fraction coverage for pairwise matches:      0.55
INFO - Configuration - Merge threshold for clusters:                0.001
INFO - Configuration - Minimum cluster size for annotation:         100
INFO - Configuration - BLAST e-value threshold for annotation:      10
INFO - Configuration - Repeat database for annotation:              /home/eric/tigriopus_genome/ArthroTE.fa
INFO - Configuration - Log file for clustering/merging results:     ArthroTE_300k_t_cluster_report.txt
INFO - Transposome::Run::Blast::run_allvall_blast started at:   28-05-2015 23:49:52.
INFO - Transposome::Run::Blast::run_allvall_blast finished running mgblast on 300000 sequences in 17.51 minutes.
INFO - Transposome::Run::Blast::run_allvall_blast completed at: 29-05-2015 00:07:22. Final output file is:
AB_150k.interleaved_allvall_blast.bln.
INFO - Transposome::PairFinder::parse_blast started at:   29-05-2015 00:07:22.
INFO - Transposome::PairFinder::parse_blast completed at: 29-05-2015 08:50:10.
INFO - Final output files are:
AB_150k.interleaved_allvall_blast_louvain.int,
AB_150k.interleaved_allvall_blast_louvain.idx,
AB_150k.interleaved_allvall_blast_louvain.edges.
INFO - Transposome::Cluster::louvain_method started at:         29-05-2015 08:50:17.
ERROR - Louvain 'community' failed. Caught error: "/root/perl5/perlbrew/perls/perl-5.20.2/bin/louvain_community AB_300k_results_out/AB_150k.interleaved_allvall_blast_louvain.bin -l -1 -w AB_300k_results_out/AB_150k.interleaved_allvall_blast_louvain.tree.weights -v >AB_300k_results_out/AB_150k.interleaved_allvall_blast_louvain.tree 2>AB_300k_results_out/AB_150k.interleaved_allvall_blast_louvain.tree.log" unexpectedly returned exit value 137 at /root/perl5/perlbrew/perls/perl-5.20.2/lib/site_perl/5.20.2/Transposome/Cluster.pm line 128.
```

**Comment by sestaton** [comment]
You are probably running out of memory (or possibly disk space). The file "AB_150k.interleaved_allvall_blast_louvain.tree.log" may have more information. My suggestion is to try first with 100k reads and watch the resource usage. That is what I usually do. That will tell you what resources are required for running analyses with a larger number of reads.

By the way, what kind of data is this? Transposome is designed to work this whole genome shotgun data.

**Comment by etwatson** [comment]
I'll try again with fewer reads. AB_150k.interleaved_allvall_blast_louvain.tree.log reads:
```
Begin: Fri May 29 08:54:28 2015
level 0:
  start computation: Fri May 29 08:54:49 2015
  network size: 371370278 nodes, 371370280 links, 9.72743e+10 weight.
Killed
```

**Comment by sestaton** [comment]
In my experience, that error indicates that memory could not be allocated for the clustering step. This can be solved by either using fewer reads or filtering out simple repeats.

This is very surprising given the number of reads in the analysis so I will investigate if there is something else that may be contributing to the issues.

**Comment by etwatson** [comment]
I've now reduced the number of reads down to a total of 100,000 (245 mb genome) and I am getting a repeat fraction of 100% with a cluster size of 100. That is odd, so I'm trying cluster sizes of 200, 500, and 1000 on a smaller set. I suppose in the end, I could include estimates from more reads by resampling a small set and averaging across them.

```
INFO - Results - Total sequences:                        100000
INFO - Results - Total sequences clustered:              99808
INFO - Results - Total sequences unclustered:            192
INFO - Results - Repeat fraction from clusters:          0.99808
INFO - Results - Singleton repeat fraction:              1.11458333333333
INFO - Results - Total repeat fraction:                  1.00022
INFO - Results - Total repeat fraction from annotations: 0.998079999996007

```

**Comment by sestaton** [comment]
There appears to be something odd with your data. Essentially every single sequence is clustered, which is not what you would expect for random shotgun data. Modifying the cluster size for annotation won't change the results much. What kind of data is this?

**Comment by etwatson** [comment]
DNA preps are from ~300 bulk-extracted wild individuals (whole organism) then shotgun sequenced (Illumina PE).

**Comment by etwatson** [comment]
The clustering issue is my fault. My script to interleave F and R reads was sampling and interleaving only F reads. Sorry to bother you with this issue!

**Comment by sestaton** [comment]
Thanks for following up on this! I was a bit puzzled as to why the pooled samples would not work as expected. By the way, [Pairfq](https://github.com/sestaton/Pairfq) is pretty handy for dealing with paired-end files. To interleave reads, you can use the [joinpairs](https://github.com/sestaton/Pairfq/wiki/joinpairs) command, and you can actually do this from the command line without installing anything. For example,

    curl -sL git.io/pairfq_lite | perl - joinpairs -f seqs1.fq.gz -r seqs2.fq.gz -o seqs_interl.fq

That would interleave two files and save the output as `seqs_interl.fq`. The input can be fasta/q and compressed (it can compress the output as well).

**Comment by aleksberic** [comment]
Hi, 

For me as well clustering is failing after almost a day of running, but the error I get is the following

Louvain 'community' failed. Caught error: "/usr/local/bin/louvain_community sample.fastq.interleave.500k.fa_PID90_COV55/sample_R1_allvall_blast_louvain.bin -l -1 -w sample.fastq.interleave.500k.fa_PID90_COV55/sample_R1_allvall_blast_louvain.tree.weights -v >sample.fastq.interleave.500k.fa_PID90_COV55/sample_R1_allvall_blast_louvain.tree 2>sample.fastq.interleave.500k.fa_PID90_COV55/sample_R1_allvall_blast_louvain.tree.log" unexpectedly returned exit value 139 at /usr/local/share/perl5/Transposome/Cluster.pm line 137.

I have many samples for which I've done the analysis, and most of them ran fine, but a couple fail with the mentioned error.
I'd appreciate help if anyone knows what might be going wrong.

Thanks

**Comment by sestaton** [comment]
Hi @aleksberic, Can you open a new issue? This one is closed and likely unrelated (unless you followed the conversation and ruled out the problem mentioned here). Thanks.

**Comment by aleksberic** [comment]
Sure, I made a new one. Thanks
