### ISSUE TITLE
PairFinder error

### ISSUE THREAD

**Issue by PolinaN** [sestaton/Transposome#35]
Hi,

I have the following error:
INFO - Transposome::PairFinder::parse_blast started at:   17-11-2016 16:26:39.
ERROR - 'SRR1231554.3462223/2   150     128     72      SRR1231554.2302746

I assume that the problem might be with my input format, but I don't see where.
Here is an example of my input fasta file:
>SRR1231554.1121/1
TACCCAGAGCTGTCTAAAAGGACATTCACTTCATAAGTCTGCATATATACATTCCTGTTACAATATACAGTAACTGTTCGTTTCACAATAAAAACTTTCATTAATAAAATCAGTCCTGGAGCTCCAGTCATGTGACTTTGCCTAGGCTGA
>SRR1231554.1121/2
ATTACGAAACGAAACGGAACACATTTTTTGACGGCGCACAAGTCTACCTGCCTGCAGAGGGTTGATGACATCATCTCAGCCTAGGCAAAGTAACACCACTGGAGCTCCCGGACTGGTTTTATTTATGAAAGTTTTTATTTTTTAAAGAAA
>SRR1231554.1405/1
AATTGATAAATTGAGGACAAGTATGCCTGGAGGTTTCCCATACCTCCTTAACGGCACAGGGACACACCAGAAGCCCAACACAATGGCAGCTGAACACCCTCTTTGTGTATATTTTCCCTTTTACAATGTAATGCAAGTTCATTTTATTTT
>SRR1231554.1405/2
GATTTACATATACTTTAATAATGCTTAGGGTCTCTTTGAGTGATCTTGGTTGTAGAACATCCTAAAAATAAAATGAACTTGCATTACATTGTAAAAGGGAAAATATACACAAAGAGGGTGTTCAGCTGCCATTGTGTTGGGCTTCTGGTG

Could you please help me to figure out what is wrong here?
Thank you,
Polina

**Comment by sestaton** [comment]
Hi Polina,

Your input data is not valid FASTA which is causing the error. There should be a ">" symbol before the sequence name, like so:

    >SRR1231554.1121/1
    TACCCAGAGCTGTCTAAAAGGACATTCACTTCATAAGTCTGCATATATACATTCCTGTTACAATATACAGTAACTGTTCGTTTCACAATAAAAACTTTCATTAATAAAATCAGTCCTGGAGCTCCAGTCATGTGACTTTGCCTAGGCTGA
    >SRR1231554.1121/2
    ATTACGAAACGAAACGGAACACATTTTTTGACGGCGCACAAGTCTACCTGCCTGCAGAGGGTTGATGACATCATCTCAGCCTAGGCAAAGTAACACCACTGGAGCTCCCGGACTGGTTTTATTTATGAAAGTTTTTATTTTTTAAAGAAA

The data must have gotten corrupted somehow during processing. Please let me know if I can help further.

Thanks,
Evan

**Comment by PolinaN** [comment]
Hi Evan,

thank you for your reply. No, unfortunately this is not the issue. I had “>” symbol before the sequence name, it got truncated while copy pasting here, sorry for that.
What else do you think can be a problem?

Here is the blastN output:
SRR1231554.1405/1       150     150     65      SRR1231554.1405/2       150     65      150     100.00  342     1e-42   -
SRR1231554.2950/1       150     150     71      SRR1231554.2950/2       150     71      150     96.25   295     7e-32   -
SRR1231554.3224/1       150     150     80      SRR1231554.3224/2       150     78      148     100.00  281     1e-33   -

and here is the log:
INFO - ======== Transposome version: 0.09.7 (started at: 18-11-2016 08:12:08) ========
INFO - Configuration - Log file for monitoring progress and errors: transposome_run_log.txt
INFO - Configuration - Sequence file:                               /scratch/neobatrachus/raw/Nparkerii_subsample100K.100000.fasta
INFO - Configuration - Sequence format:                             fasta
INFO - Configuration - Sequence number for each BLAST process:      50000
INFO - Configuration - Number of CPUs per thread:                   1
INFO - Configuration - Number of threads:                           12
INFO - Configuration - Output directory:                            transposome100Knp
INFO - Configuration - In-memory analysis:                          1
INFO - Configuration - Percent identity for matches:                90
INFO - Configuration - Fraction coverage for pairwise matches:      0.55
INFO - Configuration - Merge threshold for clusters:                0.001
INFO - Configuration - Minimum cluster size for annotation:         100
INFO - Configuration - BLAST e-value threshold for annotation:      10
INFO - Configuration - Repeat database for annotation:              /scratch/neobatrachus/transposome/RepBase21.09.fasta/tmpxen.ref
INFO - Configuration - Log file for clustering/merging results:     transposome_cluster_log.txt
INFO - Transposome::Run::Blast::run_allvall_blast started at:   18-11-2016 08:12:08.
INFO - Transposome::Run::Blast::run_allvall_blast finished running mgblast on 200000 sequences in 1.37 minutes.
INFO - Transposome::Run::Blast::run_allvall_blast completed at: 18-11-2016 08:13:31. Final output file is:
Nparkerii_subsample100K.100000_allvall_blast.bln.
INFO - Transposome::PairFinder::parse_blast started at:   18-11-2016 08:13:31.
ERROR - 'SRR1231554.5711141/2   150     133     44    
Thank you,
Polina

**Comment by sestaton** [comment]
Hi Polina,

It looks like the output got truncated, did the last line in the log read as follows?

    ERROR - 'SRR1231554.5711141/2 150 133 44

Or, was there more to it? This looks like there might have been an error with the format. Also, how big is the "Nparkerii_subsample100K.100000_allvall_blast.bln" file? I can make a place for you to drop it so I can take a look because that might be the best way to figure it out.

Thanks,
Evan

**Comment by PolinaN** [comment]
The whole output folder is 17M:
17M Nov 18 15:36 transposome100Knp.tar.gz
 That would be great, thank you

**Comment by sestaton** [comment]
Hi Polina,

I made a server for you to drop the file at: polina@107.170.218.212
passwd: O0nnblZJ9UIgNfC7c

If you can transfer the file, and maybe the sequences you are using also, I'll take a look.

Thanks,
Evan

**Comment by PolinaN** [comment]
Hi Evan,

sorry for the delay. I’ve transferred the files.

Thank you for your help,
Polina

**Comment by sestaton** [comment]
Hi Polina,

The sequence data looks fine but there is indeed a bunch of unprintable noise that filled up the BLAST file and the log so there must have been something odd coming from the terminal or the system. Hard to say what it was, but the good news is the process completed in just under 10 minutes. I won't post the results here to keep your results from being shared, but if you email me ("statonse at gmail dot com") I'll send them to you.

For other experiments, my only advice is to maybe update the code to the latest version and just try again. Since there is nothing to be done here I'm going to close this, but if you see this issue again please comment and I'll re-open it and investigate further.

Thanks,
Evan
