### ISSUE TITLE
A error about convert.

### ISSUE THREAD

**Issue by Jerrywang-evo** [sestaton/Transposome#42]
Hi,
I run the Transposome and it seems I met the problem in "convert" part:

> Louvain 'convert' failed. Caught error: "/home/wangjy/perl5/bin/louvain_convert -i . -o maize_transposome_results_out_100k_8-21/.bin -w maize_transposome_results_out_100k_8-21/.tree.weights" died to signal "ABRT" (6) and dumped core at /home/wangjy/perl5/lib/perl5/Transposome/Cluster.pm line 129.

I use "pairfq joinpairs" to obtain the single merged pair-end .fastq and converted that into .fasta file as input (which contains only 500,000 reads), and the TE annotation file was derived from my own reference genome annotation.

Could someone helps me deal with this issue, thanks so much..

**Comment by sestaton** [comment]
Hi,

It looks like the program received the ABRT signal from the system, which suggests the program was killed. This means it likely ran out of memory or disk space. 

Can you use the program 'top' in another terminal and watch the program run? That will tell you how much of the memory is being used. 

Thanks,
Evan

**Comment by Jerrywang-evo** [comment]
> Hi,
> 
> It looks like the program received the ABRT signal from the system, which suggests the program was killed. This means it likely ran out of memory or disk space.
> 
> Can you use the program 'top' in another terminal and watch the program run? That will tell you how much of the memory is being used.
> 
> Thanks,
> Evan

Thanks~ but I only used 1 cpu and 1 thread, and I always used this server on many high memory cost tasks..it seems not that matter..maybe I have set the wrong .yml file? Here is:

> `blast_input:
  - sequence_file:      GX.500K.fas
  - sequence_format:    fasta
  - sequence_num:       500000
  - cpu:                1
  - thread:             1
  - output_directory:   GX.result
clustering_options:
  - in_memory:          1
  - percent_identity:   90
  - fraction_coverage:  0.55
  - merge_threshold:    100
annotation_input:
  - repeat_database:   refTEs.fasta
annotation_options:
  - cluster_size:       100
  - blast_evalue:       10
output:
  - run_log_file:       gxlog.txt
  - cluster_log_file:   gxreport.txt`

**Comment by sestaton** [comment]
I hope you were able to find a solution. Please re-open the issue if you need more help.
