### ISSUE TITLE
[mgblast] FATAL ERROR: CoreLib [001.000]  Failed to allocate 67108864 bytes

### ISSUE THREAD

**Issue by QianghuiZhu** [sestaton/Transposome#44]
Hi! 

While I run Transposome, and I got the following error: 

INFO - ======== Transposome version: 0.12.1 (started at: 13-09-2021 09:46:13) ========
INFO - Configuration - Log file for monitoring progress and errors: ERR276219_log.txt
INFO - Configuration - Sequence file:                               ERR276219_interl.fq.gz
INFO - Configuration - Sequence format:                             fastq
INFO - Configuration - Sequence number for each BLAST process:      50000
INFO - Configuration - Number of CPUs per thread:                   2
INFO - Configuration - Number of threads:                           16
INFO - Configuration - Output directory:                            ERR276219_results_out
INFO - Configuration - In-memory analysis:                          1
INFO - Configuration - Percent identity for matches:                90
INFO - Configuration - Fraction coverage for pairwise matches:      0.55
INFO - Configuration - Merge threshold for clusters:                0.001
INFO - Configuration - Minimum cluster size for annotation:         100
INFO - Configuration - BLAST e-value threshold for annotation:      10
INFO - Configuration - Repeat database for annotation:              /public/home/casdao/kdylvfenghua/kdyzhuqianghui19/data/ARS1/repeat-V2/goats-te-seq.fa
INFO - Configuration - Log file for clustering/merging results:     ERR276219_cluster_report.txt
INFO - Transposome::Run::Blast::run_allvall_blast started at:   13-09-2021 09:46:13.
[mgblast] FATAL ERROR: CoreLib [001.000]  Failed to allocate 67108864 bytes
[mgblast] FATAL ERROR: CoreLib [001.000]  Failed to allocate 67108864 bytes
[mgblast] FATAL ERROR: CoreLib [001.000]  Failed to allocate 67108864 bytes
...

I'm sorry, but is there anything wrong while using mgblast? But it worked well while I run mgblast on command line separately.  Is there anything wrong else?
Thank you!

**Comment by sestaton** [comment]
It appears that the program is running out of memory:

     Failed to allocate 67108864 bytes

To confirm, I suggest you downsample the data to a small subset and try again. Typically you only need a small amount of reads (100k - 500k) for accurate predictions.

Please see the examples on the wiki for downsampling sequence files: https://github.com/sestaton/Transposome/wiki/API-Tutorial#seqex3

I am confident that should solve the problem.
